name: workflow_1

on: push

jobs:
  workflow_1:
    name: workflow_1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print test
        run: python test_code.py